# Generated by Django 5.2.6 on 2025-10-03 00:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Galaxy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('image_url', models.URLField(blank=True, null=True, verbose_name='URL изображения')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна ли услуга')),
            ],
            options={
                'verbose_name': 'Галактика',
                'verbose_name_plural': 'Галактики',
                'db_table': 'galaxies',
            },
        ),
        migrations.CreateModel(
            name='GalaxyRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('deleted', 'Удалена'), ('submitted', 'Сформирована'), ('completed', 'Завершена'), ('rejected', 'Отклонена')], default='draft', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата формирования')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата завершения')),
                ('telescope', models.CharField(max_length=255, verbose_name='Телескоп')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_requests', to=settings.AUTH_USER_MODEL, verbose_name='Создатель')),
                ('moderator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='moderated_requests', to=settings.AUTH_USER_MODEL, verbose_name='Модератор')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
                'db_table': 'galaxy_requests',
            },
        ),
        migrations.CreateModel(
            name='GalaxiesInRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('magnitude', models.FloatField(verbose_name='Видимая звездная величина')),
                ('distance', models.FloatField(verbose_name='Расстояние (Мпк)')),
                ('galaxy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='distance_calculation.galaxy')),
                ('galaxy_request', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='galaxies', to='distance_calculation.galaxyrequest')),
            ],
            options={
                'verbose_name': 'Галактика в заявке',
                'verbose_name_plural': 'Галактики в заявке',
                'db_table': 'galaxies_in_request',
            },
        ),
    ]
