# Generated by Django 5.2.7 on 2025-11-04 16:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Galaxy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('image_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Имя файла в MinIO')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна ли услуга')),
            ],
            options={
                'verbose_name': 'Галактика',
                'verbose_name_plural': 'Галактики',
                'db_table': 'galaxies',
            },
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=150, unique=True, verbose_name='Имя пользователя')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='Имя')),
                ('last_name', models.CharField(blank=True, max_length=30, verbose_name='Фамилия')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Менеджер (staff)')),
                ('is_superuser', models.BooleanField(default=False, verbose_name='Администратор (superuser)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активный пользователь')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='Дата регистрации')),
                ('groups', models.ManyToManyField(blank=True, help_text='Группы, к которым принадлежит пользователь.', related_name='distance_calculation_users', to='auth.group')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Права пользователя.', related_name='distance_calculation_users_permissions', to='auth.permission')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
        migrations.CreateModel(
            name='GalaxyRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('deleted', 'Удалена'), ('submitted', 'Сформирована'), ('completed', 'Завершена'), ('rejected', 'Отклонена')], default='draft', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата формирования')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата завершения')),
                ('telescope', models.CharField(blank=True, max_length=255, null=True, verbose_name='Телескоп')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_requests', to=settings.AUTH_USER_MODEL, verbose_name='Создатель')),
                ('moderator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderated_requests', to=settings.AUTH_USER_MODEL, verbose_name='Модератор')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
                'db_table': 'galaxy_requests',
            },
        ),
        migrations.CreateModel(
            name='GalaxiesInRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('magnitude', models.FloatField(blank=True, null=True, verbose_name='Видимая звездная величина')),
                ('distance', models.FloatField(blank=True, null=True, verbose_name='Расстояние (Мпк)')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('galaxy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='distance_calculation.galaxy')),
                ('galaxy_request', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='galaxies', to='distance_calculation.galaxyrequest')),
            ],
            options={
                'verbose_name': 'Галактика в заявке',
                'verbose_name_plural': 'Галактики в заявке',
                'db_table': 'galaxies_in_request',
            },
        ),
    ]
