# Generated by Django 5.2.6 on 2025-10-03 02:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distance_calculation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='galaxiesinrequest',
            name='added_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='galaxiesinrequest',
            name='distance',
            field=models.FloatField(blank=True, null=True, verbose_name='Расстояние (Мпк)'),
        ),
        migrations.AlterField(
            model_name='galaxiesinrequest',
            name='magnitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Видимая звездная величина'),
        ),
    ]
