# Generated by Django 5.2.7 on 2025-10-15 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distance_calculation', '0002_galaxiesinrequest_added_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='galaxy',
            name='image_url',
        ),
        migrations.AddField(
            model_name='galaxy',
            name='image_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Имя файла в MinIO'),
        ),
    ]
