# Generated by Django 5.2.7 on 2025-10-21 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distance_calculation', '0003_remove_galaxy_image_url_galaxy_image_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galaxyrequest',
            name='telescope',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Телескоп'),
        ),
    ]
